SET MODE Oracle;

CREATE TABLE APLICACIONES (
	ID_APLICACION NUMBER(4,0) NOT NULL PRIMARY KEY,
    NOMBRE_APLICACION VARCHAR2(100) NOT NULL
);
CREATE TABLE USUARIOS (
	ID_USUARIO VARCHAR2(250),
	PASS_USER VARCHAR2(250),
	NOMBRE_APELLIDOS VARCHAR2(500),
	CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);
CREATE TABLE GRUPOS (
	ID_GRUPO NUMBER(4,0),
	NOMBRE_GRUPO VARCHAR2(100),
	CONSTRAINT PK_GRUPOS PRIMARY KEY (ID_GRUPO)
);
CREATE TABLE USUARIOS_GRUPOS (
	ID_USUARIO VARCHAR2(250),
	ID_GRUPO NUMBER(4,0),
	CONSTRAINT PK_USUARIOS_GRUPOS PRIMARY KEY (ID_USUARIO,ID_GRUPO)
);
CREATE TABLE OAUTH_CLIENT_DETAILS (
	client_id VARCHAR2(32) NOT NULL PRIMARY KEY,
	client_secret VARCHAR2(32) NOT NULL,
	scopes VARCHAR2(128) DEFAULT 'all',
	authorized_grant_types VARCHAR2(128) NOT NULL,
	access_token_validity_seconds NUMBER NOT NULL,
	refresh_token_validity_seconds NUMBER,
	id_aplicacion NUMBER(4,0) NOT NULL,
	foreign key (id_aplicacion) references APLICACIONES(ID_APLICACION)
);
CREATE TABLE GRUPOS_APLICACIONES (
	ID_GRUPO NUMBER(4,0),
	ID_APLICACION NUMBER(4,0),
	CONSTRAINT PK_GRUPOS_APLICACIONES PRIMARY KEY (ID_GRUPO,ID_APLICACION),
	foreign key (ID_APLICACION) references APLICACIONES(ID_APLICACION)
);
